name: typhon_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - minimap2
  - k8  # Required for paftools.js which comes with minimap2
  - longgf
  - samtools
  - pygtftk
  - blast
  - bedtools
  - seqkit
  - bedops
  - clustalo
  - clustalw
  - biopython
  - r-base
  - r-dplyr
  - r-tidyverse
  - r-data.table
  - r-magrittr
  - r-openxlsx
  - r-stringr
  - r-tidyr
  - bioconductor-biostrings
  - r-seqinr
  - r-pafr
  - seqtk
  - rename
  - pyyaml
  - pandas
  - openpyxl
  - openjdk=11     # Java 11 for JaffaL compatibility
  - bowtie2        # For building JaffaL indices
  # JaffaL dependencies - significantly reduces setup time
  - trimmomatic    # Read trimming tool
  - velvet         # Includes velveth and velvetg
  - oases          # Transcriptome assembler (depends on velvet)
  - blat           # Sequence alignment tool
  - bpipe          # Build system used by JaffaL
  - bbmap          # Includes dedupe, reformat, and other tools 