project:
  name: "Mouse_RNA_Fusion_Test"
  output_dir: "test_output_pipeline"
  threads: 20
  author: "Eren Ada, PhD"

input:
  fastq_dir: "test_data/FASTQ"

references:
  genome: "test_data/REFERENCES/GRCm39.primary_assembly.genome.fa"
  gtf: "test_data/REFERENCES/gencode.vM28.annotation.gtf"
  transcriptome: "test_data/REFERENCES/gencode.vM28.transcripts.fa"

modules:
  longgf:
    enabled: true
    keep_intermediate: false
    min_support: 100
    gap_threshold: 50
    junction_threshold: 100
  genion:
    enabled: true
    min_support: 1
    keep_debug: true
  jaffal:
    enabled: false
    jaffal_dir: "/path/to/jaffal/installation"

options:
  cleanup_intermediate: true
  debug: false
  keep_sam_files: true 