project:
  name: My_RNA_Fusion_Analysis
  output_dir: /path/to/output/directory
  threads: 20
  author: Your Name
input:
  fastq_dir: /path/to/fastq/files
references:
  genome: /path/to/genome.fa
  gtf: /path/to/annotation.gtf
  transcriptome: /path/to/transcripts.fa
modules:
  longgf:
    enabled: true
    keep_intermediate: false
    min_support: 100
    gap_threshold: 50
    junction_threshold: 100
  genion:
    enabled: true
    min_support: 1
    keep_debug: true
  jaffal:
    enabled: false
    jaffal_dir: /path/to/jaffal/installation
options:
  cleanup_intermediate: true
  debug: false
  keep_sam_files: true

